"""Add users table

Revision ID: 3d88c7225061
Revises: c85379e0eae8
Create Date: 2026-06-23 16:47:33.997629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d88c7225061'
down_revision: Union[str, Sequence[str], None] = 'c85379e0eae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_full_name'))
        batch_op.drop_column('currency')
        batch_op.drop_column('salary_date')
        batch_op.drop_column('full_name')
        batch_op.drop_column('salary_amount')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('salary_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('salary_date', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_full_name'), ['full_name'], unique=False)

    # ### end Alembic commands ###
